name: UTB Tracker CI

on:
  push: 
    branches: 
      main

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.USER_PASW }}
        script: |
          cd ${{ secrets.WORK_DIR}}
          git fetch origin main
          git reset --hard origin/main
          source venv/bin/activate
          pip install -r requirements.txt
          python uvicorn app.main:app --host
          sudo systemctl restart utb-tracker

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

   

    - name: Ejecutar pruebas automatizadas (Pytest)
      run: |
        python -m pytest app/tests/
